ap <- available.packages(repos="https://cloud.r-project.org")
d <- read.dcf("/Users/bbuchsbaum/code/rMVPA/DESCRIPTION")
f <- function(x) trimws(gsub("\\(.*\\)","",strsplit(gsub("\n"," ",x),",")[[1]]))
imp <- f(d[,"Imports"]); sug <- f(d[,"Suggests"])
base <- rownames(installed.packages(priority="base"))
cat("Imports not on CRAN:", setdiff(imp[!imp %in% rownames(ap)], base), "\n")
cat("Suggests not on CRAN:", setdiff(sug[!sug %in% rownames(ap)], base), "\n")
for (p in c("neuroim2","neurosurf","fmridesign","fmrilss","shard","albersdown","fmriAR","fmrihrf","sparsediscrim","sda","spls","rrpack","io","ffmanova","Rfit","furrr","futile.logger","modelr","memoise")) cat(p, if (p %in% rownames(ap)) ap[p,"Version"] else "NOT ON CRAN", "\n")
cat("Installed neuroim2:", as.character(packageVersion("neuroim2")), "\n")
for (p in c("neurosurf","fmridesign","fmrilss","shard","fmrihrf","fmriAR")) cat(p, "installed:", tryCatch(as.character(packageVersion(p)), error=function(e) "no"), "\n")
cat(R.version.string,"\n")
