suppressMessages(pkgload::load_all("/Users/bbuchsbaum/code/rMVPA", quiet=TRUE))
futile.logger::flog.threshold(futile.logger::ERROR)
set.seed(1)
ds <- gen_sample_dataset(c(9,9,9), 100, nlevels=4, blocks=5)
cv <- blocked_cross_validation(ds$design$block_var)
ms <- mvpa_model(load_model("corclass"), ds$dataset, ds$design, "classification", crossval=cv)
Rprof("prof.out", interval=0.005, memory.profiling=FALSE)
t <- system.time(r <- run_searchlight(ms, radius=3, engine="legacy", verbose=FALSE))
Rprof(NULL)
print(t)
s <- summaryRprof("prof.out")
print(head(s$by.self, 30))
tt <- s$by.total; print(head(tt[grepl("^\"(internal_crossval|train_model|fit_model|format_result|merge_results|compute_performance|extract_roi|as_roi|filter_roi|get_samples|predict|tibble|bind_rows|gc|crossval_samples|flog|duplicated|apply|tune_grid|corsimFit|prob_corsimFit|predict_corsimFit|model_fit|wrap_result|combine_standard|process_roi|fit_roi|roi_result_to_tibble|as_tibble|.validate_fit_roi_schema|series_roi|neuroim2::series_roi|performance|multiclass)",rownames(tt)),],60))
