suppressMessages(pkgload::load_all("/Users/bbuchsbaum/code/rMVPA", quiet=TRUE))
futile.logger::flog.threshold(futile.logger::ERROR)
set.seed(1)
ds <- gen_sample_dataset(c(10,10,10), 100, nlevels=4, blocks=5)
cv <- blocked_cross_validation(ds$design$block_var)
ms <- mvpa_model(load_model("corclass"), ds$dataset, ds$design, "classification", crossval=cv)
Rprof("prof.out", interval=0.005)
t <- system.time(run_searchlight(ms, radius=3, method="standard", engine="legacy", verbose=FALSE))
Rprof(NULL); print(t)
s <- summaryRprof("prof.out")
print(head(s$by.self, 30)); print(head(s$by.total, 60))
ms2 <- mvpa_model(load_model("sda_notune"), ds$dataset, ds$design, "classification", crossval=cv)
print(system.time(run_searchlight(ms2, radius=3, method="standard", engine="auto", verbose=FALSE)))
print(system.time(run_searchlight(ms2, radius=3, method="standard", engine="legacy", verbose=FALSE)))
ms3 <- mvpa_model(load_model("svmLinear"), ds$dataset, ds$design, "classification", crossval=cv)
print(tryCatch(system.time(run_searchlight(ms3, radius=3, method="standard", engine="auto", verbose=FALSE)), error=function(e) conditionMessage(e)))
