# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages: bbuchsbaum/neuroim2


warnings_are_errors: false


Imports: neuroim2
  
Remotes: bbuchsbaum/neuroim2
  

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(type="all")'


env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE