#' ROI-by-ROI similarity through a correlated model-RDM space
#'
#' Projects ROI RDM vectors into the subspace spanned by one or more model RDMs,
#' decorrelates that model space, and compares ROIs through their model-space
#' fingerprints.
#'
#' @details
#' This helper implements a projection-based second-order RSA summary for the
#' common situation where several model RDMs are correlated. Let `Y` be the
#' lower-triangle ROI RDM matrix, with RDM cells in rows and ROIs in columns,
#' and let `X` be the corresponding matrix of model RDM vectors. After optional
#' rank transformation and column standardization, the function builds an
#' orthonormal basis `Q` for the column space of `X` and computes
#'
#' \deqn{F = Y' Q / \sqrt{p - 1}}
#'
#' where `p` is the number of retained RDM cells. Rows of `F` are decorrelated
#' ROI model-space fingerprints. The strength-sensitive ROI-by-ROI similarity is
#'
#' \deqn{S_{model} = F F'}
#'
#' which is equivalent to \eqn{Y' P_X Y / (p - 1)}. The profile-only similarity
#' is the cosine similarity between rows of `F`.
#'
#' With `basis = "pca"`, the first component is often the common model axis
#' when all model RDMs are positively correlated, and later components describe
#' differentiating model contrasts. With `basis = "qr"`, the axes are an
#' orthonormal basis generated by QR decomposition of the supplied model order.
#'
#' @param roi_rdms ROI RDM vectors. Accepted forms are a matrix with RDM cells
#'   in rows and ROIs in columns, a named list of numeric vectors, a tibble/data
#'   frame with columns `roinum` and `rdm_vec` as returned by
#'   \code{\link{feature_rsa_rdm_vectors}}, or a `regional_mvpa_result`
#'   containing stored feature-RSA RDM vectors.
#' @param model_rdms Named list of square symmetric model RDM matrices or
#'   `dist` objects, or a numeric matrix with RDM cells in rows and model RDMs
#'   in columns.
#' @param method Similarity scale used before projection. `"pearson"` centers
#'   and scales numeric RDM values. `"spearman"` rank-transforms each RDM vector
#'   before centering and scaling.
#' @param basis Basis for the model subspace. `"pca"` orders orthogonal axes by
#'   variance in the model-RDM correlation matrix. `"qr"` uses a QR basis tied
#'   to the supplied model order.
#' @param use Missing-value policy. `"complete.obs"` removes RDM cells with any
#'   non-finite model or ROI value before fitting the subspace. `"everything"`
#'   requires all model and ROI vectors to be finite.
#' @param tol Numerical tolerance for dropping near-zero model-space dimensions
#'   and detecting zero-norm ROI fingerprints.
#' @param return_projected Logical; if `TRUE`, include the projected ROI RDM
#'   vectors and residual ROI RDM vectors in the returned object.
#'
#' @return An object of class `rdm_model_space_connectivity`, a list with:
#' \describe{
#'   \item{similarity}{Strength-sensitive ROI-by-ROI similarity through the
#'     full model-RDM subspace.}
#'   \item{profile_similarity}{Cosine similarity between ROI model-space
#'     fingerprints, ignoring overall model-alignment strength.}
#'   \item{component_similarity}{Named list of rank-1 ROI-by-ROI matrices, one
#'     per orthogonal model-space axis.}
#'   \item{common_similarity}{The first component matrix, useful for the shared
#'     model axis under `basis = "pca"`.}
#'   \item{difference_similarity}{Sum of all components after the first.}
#'   \item{raw_similarity}{Second-order ROI similarity before model projection.}
#'   \item{residual_similarity}{ROI similarity outside the model-RDM subspace.}
#'   \item{scores}{ROI-by-axis fingerprint matrix `F`.}
#'   \item{raw_model_scores}{ROI-by-original-model correlation matrix.}
#'   \item{model_axis_cor}{Correlation of orthogonal model axes with original
#'     model RDMs, used to interpret the axes.}
#' }
#' @export
#'
#' @examples
#' set.seed(1)
#' n <- 8
#' p <- n * (n - 1) / 2
#' model_vecs <- matrix(rnorm(p * 4), p, 4)
#' colnames(model_vecs) <- paste0("A", 1:4)
#' roi_vecs <- model_vecs %*% matrix(rnorm(4 * 5), 4, 5) +
#'   matrix(rnorm(p * 5, sd = 0.2), p, 5)
#' colnames(roi_vecs) <- paste0("ROI", 1:5)
#'
#' conn <- rdm_model_space_connectivity(roi_vecs, model_vecs)
#' conn$similarity
rdm_model_space_connectivity <- function(roi_rdms,
                                         model_rdms,
                                         method = c("pearson", "spearman"),
                                         basis = c("pca", "qr"),
                                         use = c("complete.obs", "everything"),
                                         tol = 1e-8,
                                         return_projected = FALSE) {
  method <- match.arg(method)
  basis <- match.arg(basis)
  use <- match.arg(use)

  if (!is.numeric(tol) || length(tol) != 1L || !is.finite(tol) || tol <= 0) {
    stop("`tol` must be a positive finite scalar.", call. = FALSE)
  }
  if (!is.logical(return_projected) || length(return_projected) != 1L || is.na(return_projected)) {
    stop("`return_projected` must be TRUE or FALSE.", call. = FALSE)
  }

  roi <- .rdm_model_space_parse_roi_rdms(roi_rdms)
  model <- .rdm_model_space_parse_model_rdms(model_rdms)

  if (nrow(roi$vectors) != nrow(model$vectors)) {
    stop(
      "`roi_rdms` and `model_rdms` must have the same lower-triangle vector length.",
      call. = FALSE
    )
  }

  all_vecs <- cbind(model$vectors, roi$vectors)
  finite_rows <- stats::complete.cases(all_vecs)
  if (identical(use, "everything") && !all(finite_rows)) {
    stop("All model and ROI RDM vector entries must be finite when `use = \"everything\"`.", call. = FALSE)
  }
  if (!all(finite_rows)) {
    model$vectors <- model$vectors[finite_rows, , drop = FALSE]
    roi$vectors <- roi$vectors[finite_rows, , drop = FALSE]
  }

  p <- nrow(model$vectors)
  if (p < 2L) {
    stop("At least two finite RDM cells are required after missing-value handling.", call. = FALSE)
  }

  X <- .rdm_standardize_columns(model$vectors, similarity = method, tol = tol, label = "model_rdms")
  Y <- .rdm_standardize_columns(roi$vectors, similarity = method, tol = tol, label = "roi_rdms")

  raw_model_scores <- crossprod(Y, X) / (p - 1L)
  dimnames(raw_model_scores) <- list(roi$labels, model$labels)

  basis_fit <- .rdm_model_space_basis(X, basis = basis, tol = tol)
  Q <- basis_fit$Q
  axis_names <- basis_fit$axis_names
  colnames(Q) <- axis_names

  scores <- crossprod(Y, Q) / sqrt(p - 1L)
  dimnames(scores) <- list(roi$labels, axis_names)

  similarity <- tcrossprod(scores)
  dimnames(similarity) <- list(roi$labels, roi$labels)

  raw_similarity <- crossprod(Y) / (p - 1L)
  dimnames(raw_similarity) <- list(roi$labels, roi$labels)

  projected <- Q %*% crossprod(Q, Y)
  residual <- Y - projected
  residual_similarity <- crossprod(residual) / (p - 1L)
  dimnames(residual_similarity) <- list(roi$labels, roi$labels)

  component_similarity <- lapply(seq_len(ncol(scores)), function(i) {
    mat <- tcrossprod(scores[, i, drop = FALSE])
    dimnames(mat) <- list(roi$labels, roi$labels)
    mat
  })
  names(component_similarity) <- axis_names

  norms <- sqrt(rowSums(scores^2))
  profile_scores <- scores
  keep <- is.finite(norms) & norms > tol
  profile_scores[keep, ] <- profile_scores[keep, , drop = FALSE] / norms[keep]
  profile_scores[!keep, ] <- NA_real_
  profile_similarity <- tcrossprod(profile_scores)
  dimnames(profile_similarity) <- list(roi$labels, roi$labels)

  model_axis_cor <- .rdm_model_space_col_cor(Q, X)
  dimnames(model_axis_cor) <- list(axis_names, model$labels)

  common_similarity <- component_similarity[[1L]]
  difference_similarity <- if (length(component_similarity) > 1L) {
    Reduce(`+`, component_similarity[-1L])
  } else {
    matrix(0, nrow = nrow(similarity), ncol = ncol(similarity),
           dimnames = dimnames(similarity))
  }

  out <- list(
    similarity = similarity,
    profile_similarity = profile_similarity,
    component_similarity = component_similarity,
    common_similarity = common_similarity,
    difference_similarity = difference_similarity,
    raw_similarity = raw_similarity,
    residual_similarity = residual_similarity,
    scores = scores,
    raw_model_scores = raw_model_scores,
    model_axis_cor = model_axis_cor,
    model_cor = stats::cor(X),
    eigenvalues = basis_fit$eigenvalues,
    rank = ncol(Q),
    basis = basis,
    method = method,
    n_pairs_total = nrow(all_vecs),
    n_pairs_used = p,
    roi_labels = roi$labels,
    model_labels = model$labels
  )

  if (isTRUE(return_projected)) {
    colnames(projected) <- roi$labels
    colnames(residual) <- roi$labels
    out$projected_vectors <- projected
    out$residual_vectors <- residual
  }

  structure(out, class = c("rdm_model_space_connectivity", "list"))
}

#' @export
print.rdm_model_space_connectivity <- function(x, ...) {
  cat("RDM Model-Space Connectivity\n")
  cat("  method:       ", x$method, "\n", sep = "")
  cat("  basis:        ", x$basis, "\n", sep = "")
  cat("  ROIs:         ", length(x$roi_labels), "\n", sep = "")
  cat("  model RDMs:   ", length(x$model_labels), "\n", sep = "")
  cat("  rank:         ", x$rank, "\n", sep = "")
  cat("  RDM cells:    ", x$n_pairs_used, "/", x$n_pairs_total, "\n", sep = "")
  invisible(x)
}

.rdm_model_space_parse_roi_rdms <- function(roi_rdms) {
  if (is.data.frame(roi_rdms) && "rdm_vec" %in% names(roi_rdms)) {
    if ("observation_index" %in% names(roi_rdms)) {
      .feature_rsa_validate_obs_order(
        roi_rdms$observation_index,
        fn_label = "rdm_model_space_connectivity"
      )
    }
    lens <- vapply(roi_rdms$rdm_vec, length, integer(1))
    if (length(unique(lens)) != 1L) {
      stop("`roi_rdms$rdm_vec` entries must all have the same length.", call. = FALSE)
    }
    labels <- if ("roinum" %in% names(roi_rdms)) {
      as.character(roi_rdms$roinum)
    } else {
      as.character(seq_len(nrow(roi_rdms)))
    }
    mat <- .feature_rsa_bind_numeric_columns(lapply(roi_rdms$rdm_vec, as.numeric))
    colnames(mat) <- labels
    return(list(vectors = mat, labels = labels))
  }

  if (inherits(roi_rdms, "regional_mvpa_result")) {
    return(.rdm_model_space_parse_roi_rdms(feature_rsa_rdm_vectors(roi_rdms)))
  }

  if (is.matrix(roi_rdms) || is.data.frame(roi_rdms)) {
    mat <- as.matrix(roi_rdms)
    if (!is.numeric(mat)) {
      stop("Matrix `roi_rdms` must be numeric.", call. = FALSE)
    }
    labels <- colnames(mat)
    if (is.null(labels) || any(!nzchar(labels))) {
      labels <- paste0("ROI", seq_len(ncol(mat)))
    }
    colnames(mat) <- labels
    return(list(vectors = mat, labels = labels))
  }

  if (is.list(roi_rdms) && length(roi_rdms) > 0L) {
    lens <- vapply(roi_rdms, length, integer(1))
    if (length(unique(lens)) != 1L) {
      stop("ROI RDM vectors must all have the same length.", call. = FALSE)
    }
    mat <- .feature_rsa_bind_numeric_columns(lapply(roi_rdms, as.numeric))
    labels <- names(roi_rdms)
    if (is.null(labels) || any(!nzchar(labels))) {
      labels <- paste0("ROI", seq_along(roi_rdms))
    }
    colnames(mat) <- labels
    return(list(vectors = mat, labels = labels))
  }

  stop(
    "`roi_rdms` must be a matrix, list of numeric vectors, RDM-vector tibble, or regional_mvpa_result.",
    call. = FALSE
  )
}

.rdm_model_space_parse_model_rdms <- function(model_rdms) {
  if (is.matrix(model_rdms) || is.data.frame(model_rdms)) {
    mat <- as.matrix(model_rdms)
    if (!is.numeric(mat)) {
      stop("Matrix `model_rdms` must be numeric.", call. = FALSE)
    }
    labels <- colnames(mat)
    if (is.null(labels) || any(!nzchar(labels))) {
      labels <- paste0("model", seq_len(ncol(mat)))
    }
    colnames(mat) <- labels
    return(list(vectors = mat, labels = labels))
  }

  parsed <- .rdm_decorrelation_parse_rdms(model_rdms)
  list(vectors = parsed$vectors, labels = colnames(parsed$vectors))
}

.rdm_model_space_basis <- function(X, basis, tol) {
  if (identical(basis, "pca")) {
    G <- crossprod(X) / (nrow(X) - 1L)
    eg <- eigen(G, symmetric = TRUE)
    keep <- eg$values > tol
    if (!any(keep)) {
      stop("Model RDM space has no non-degenerate dimensions.", call. = FALSE)
    }
    values <- eg$values[keep]
    vectors <- eg$vectors[, keep, drop = FALSE]
    Q <- X %*% vectors %*% diag(1 / sqrt((nrow(X) - 1L) * values), nrow = length(values))
    axis_names <- paste0("PC", seq_along(values))
    list(Q = Q, eigenvalues = values, axis_names = axis_names)
  } else {
    qrx <- qr(X, tol = tol)
    rank_x <- qrx$rank
    if (rank_x < 1L) {
      stop("Model RDM space has no non-degenerate dimensions.", call. = FALSE)
    }
    Q <- qr.Q(qrx, complete = FALSE)[, seq_len(rank_x), drop = FALSE]
    axis_names <- paste0("QR", seq_len(rank_x))
    list(Q = Q, eigenvalues = rep(NA_real_, rank_x), axis_names = axis_names)
  }
}

.rdm_model_space_col_cor <- function(A, B) {
  denom <- sqrt(colSums(A^2)) %o% sqrt(colSums(B^2))
  out <- crossprod(A, B) / denom
  out[!is.finite(out)] <- NA_real_
  out
}
