#' @noRd
#' @keywords internal
sanitize <- function(name) {
  name <- gsub(":", ".", name)
  name <- gsub(" ", "", name)
  name <- gsub("[\\(\\)]", ".", name, perl=TRUE)
  name <- gsub(",", "_", name)
  name <- gsub("\\.$", "", name)
  name
}


#' Construct a design for an RSA (Representational Similarity Analysis) model
#'
#' This function constructs a design for an RSA model using the provided formula, data, and optional parameters.
#'
#' @param formula A formula expression specifying the dissimilarity-based regression function.
#' @param data A named list containing the dissimilarity matrices and any other auxiliary variables.
#' @param block_var An optional \code{formula}, \code{character} name or \code{integer} vector designating the block structure.
#' @param split_by An optional \code{formula} indicating grouping structure for evaluating test performance.
#' @param keep_intra_run A \code{logical} indicating whether to include within-run comparisons (default: FALSE).
#' @param nuisance Optional named list of nuisance RDMs or item-level
#'   variables using the same accepted forms as entries in \code{data}. These
#'   predictors are appended to the RSA model matrix, included in regression
#'   fits, and tagged as nuisance so \code{rsa_model(...,
#'   return_fingerprint = TRUE)} excludes them from model-space fingerprints.
#' @param pair_mask Optional logical vector in \code{dist}/lower-triangle order,
#'   or symmetric item-by-item logical matrix with a FALSE diagonal. TRUE retains
#'   that distinct-item pair. Missing values, wrong dimensions and empty selections
#'   are rejected. Intersects the existing \code{block_var} exclusion and applies
#'   identically to neural responses, predictors, nuisance terms and diagnostics.
#'   Included predictor/nuisance cells must be finite. \code{split_by} does not
#'   restrict fitted pairs. For within-recording comparisons, use a mask built
#'   from recording equality; \code{block_var} alone excludes same-block pairs.
#' @param condition_ids Optional unique IDs in the exact order of design items.
#'   Required for crossvalidated Euclidean RSA. Named RDMs and masks must match
#'   this order; these IDs identify conditions, not runs or repeated observations.
#' @return A list with class attributes "rsa_design" and "list", containing:
#'   \describe{
#'     \item{formula}{The input formula}
#'     \item{data}{The input data}
#'     \item{split_by}{The split_by formula}
#'     \item{split_groups}{Grouping structure for split_by}
#'     \item{block_var}{Block structure}
#'     \item{include}{Logical vector for including/excluding comparisons}
#'     \item{model_mat}{Model matrix generated by rsa_model_mat}
#'     \item{model_predictors}{Sanitized names of formula predictors}
#'     \item{nuisance_predictors}{Sanitized names of nuisance predictors}
#'   }
#' @details
#' The function creates an RSA design based on the input parameters. It checks the validity of the input data and
#' handles splitting conditions for evaluation of test performance. It also processes optional block structures and
#' within-run comparisons.
#' @importFrom assertthat assert_that
#' @export
#' @examples
#' dismat <- dist(matrix(rnorm(100*100), 100, 100))
#' rdes <- rsa_design(~ dismat, list(dismat=dismat))
rsa_design <- function(formula, data, block_var=NULL, split_by=NULL, keep_intra_run=FALSE, nuisance = list(),
                       pair_mask = NULL, condition_ids = NULL) {
  assert_that(purrr::is_formula(formula))
  if (!is.list(data) || is.null(names(data))) {
    stop("`data` must be a named list.", call. = FALSE)
  }
  nuisance <- if (is.null(nuisance)) list() else as.list(nuisance)
  if (length(nuisance) > 0L && (is.null(names(nuisance)) || any(!nzchar(names(nuisance))))) {
    stop("`nuisance` must be a named list when supplied.", call. = FALSE)
  }
  
  # Check that all variables are either matrices, "dist", or vectors
  nr <- sapply(c(data, nuisance), .rsa_design_entry_size)
  
  assert_that(all(nr == nr[1]), msg="all elements in 'data' and 'nuisance' must have the same number of rows")
  
  check_split <- function(split_var) {
    minSplits <- min(table(split_var))
    if (minSplits < 3) {
      stop(paste("error: splitting condition results in fewer than 3 observations in at least one set"))
    }
  }
  
  # Create split groups if split_by is provided
  split_groups <- if (!is.null(split_by)) {
    split_var <- parse_variable(split_by, data)
    split(seq_along(split_var), split_var)
  }
  
  # Process block_var if provided
  block_var <- if (!is.null(block_var)) {
    parse_variable(block_var, data)
  }
  
  # Include/exclude within-run comparisons based on keep_intra_run
  include <- if (!is.null(block_var) && !keep_intra_run) {
    as.vector(dist(block_var)) != 0
  }
  
  n_items <- as.integer(nr[1L])
  if (!is.null(condition_ids)) {
    if (!is.atomic(condition_ids) || !is.null(dim(condition_ids)) ||
        length(condition_ids) != n_items || anyNA(condition_ids) ||
        any(!nzchar(as.character(condition_ids))) || anyDuplicated(as.character(condition_ids))) {
      stop("`condition_ids` must contain one unique, nonmissing ID per design item.", call. = FALSE)
    }
    condition_ids <- as.character(condition_ids)
    for (entry in c(data, nuisance)) {
      ids <- if (inherits(entry, "dist")) attr(entry, "Labels") else
        if (is.matrix(entry)) rownames(entry) else NULL
      cols <- if (is.matrix(entry) && isSymmetric(unname(entry))) colnames(entry) else NULL
      if ((!is.null(ids) && !identical(ids, condition_ids)) ||
          (!is.null(cols) && !identical(cols, condition_ids))) {
        stop("RDM/item labels must match `condition_ids` in order.", call. = FALSE)
      }
    }
  }
  if (!is.null(pair_mask)) {
    pair_mask <- .rsa_validate_pair_mask(pair_mask, n_items, condition_ids)
    include <- if (is.null(include)) pair_mask else include & pair_mask
    if (!any(include)) stop("`pair_mask` leaves no eligible pairs.", call. = FALSE)
  }

  # Create the RSA design as a list
  des <- list(
    formula=formula,
    data=data,
    nuisance=nuisance,
    split_by=split_by,
    split_groups=split_groups,
    block_var=block_var,
    include=include,
    pair_mask=pair_mask,
    condition_ids=condition_ids
  )
  
  # Add model matrix to the design list
  mmat <- rsa_model_mat(des)
  if (!is.null(pair_mask) && any(!is.finite(unlist(mmat)))) {
    stop("Included predictor and nuisance pairs must be finite; use `pair_mask` to exclude missing cells.", call. = FALSE)
  }
  des$model_mat <- mmat
  model_names <- sanitize(labels(terms(formula)))
  nuisance_names <- sanitize(names(nuisance))
  if (anyDuplicated(c(model_names, nuisance_names))) {
    stop("Sanitized model/nuisance predictor names must be unique.",
         call. = FALSE)
  }
  des$model_predictors <- model_names
  des$nuisance_predictors <- nuisance_names
  des$predictor_roles <- stats::setNames(
    c(rep("model", length(model_names)), rep("nuisance", length(nuisance_names))),
    c(model_names, nuisance_names)
  )
  
  # Set the class attributes
  class(des) <- c("rsa_design", "list")
  
  # Return the RSA design
  des
}


#' @noRd
.rsa_design_entry_size <- function(x) {
  if (is.matrix(x)) {
    nrow(x)
  } else if (inherits(x, "dist")) {
    attr(x, "Size")
  } else if (is.vector(x)) {
    length(x)
  } else {
    stop(paste("illegal variable type", class(x)), call. = FALSE)
  }
}

#' @noRd
.rsa_validate_pair_mask <- function(pair_mask, n_items, condition_ids = NULL) {
  if (!is.logical(pair_mask) || anyNA(pair_mask)) {
    stop("`pair_mask` must be logical without missing values.", call. = FALSE)
  }
  if (is.matrix(pair_mask)) {
    if (!identical(dim(pair_mask), c(n_items, n_items)) ||
        !isSymmetric(unname(pair_mask)) || any(diag(pair_mask))) {
      stop("Matrix `pair_mask` must be square, symmetric, item-aligned, with a FALSE diagonal.", call. = FALSE)
    }
    if (!is.null(condition_ids)) {
      for (ids in dimnames(pair_mask)) {
        if (!is.null(ids) && !identical(ids, condition_ids)) {
          stop("`pair_mask` labels must match `condition_ids` in order.", call. = FALSE)
        }
      }
    }
    pair_mask <- pair_mask[lower.tri(pair_mask)]
  } else if (!is.null(dim(pair_mask)) || length(pair_mask) != choose(n_items, 2)) {
    stop("Vector `pair_mask` must have choose(n_items, 2) entries in lower-triangle order.", call. = FALSE)
  }
  unname(pair_mask)
}

#' @noRd
.rsa_design_vectorize_entries <- function(entries, include = NULL) {
  vmatlist <- lapply(entries, function(v) {
    if (inherits(v, "dist")) {
      as.vector(v)  # class "dist"
    } else if (is.matrix(v) && isSymmetric(v)) {
      v[lower.tri(v)]
    } else {
      as.vector(dist(v))
    }
  })

  if (!is.null(include)) {
    vmatlist <- lapply(vmatlist, function(v) v[include])
  }

  names(vmatlist) <- sanitize(names(entries))
  vmatlist
}

#' Construct a model matrix for an RSA (Representational Similarity Analysis) design
#'
#' This function constructs a model matrix for the given RSA design by processing distance matrices and other variables.
#'
#' @param rsa_des An RSA design object created by \code{rsa_design()}, containing formula, data, and optional parameters.
#' @return A named list of vectors, where:
#'   \itemize{
#'     \item Names correspond to sanitized variable names from the formula
#'     \item Each vector is the processed version of the corresponding input data
#'     \item For distance matrices, only the lower triangle is included
#'     \item If rsa_des$include is specified, vectors are subset accordingly
#'   }
#' @details
#' The function takes an RSA design object as input and processes the distance matrices and other variables to
#' construct a model matrix. It handles different types of input matrices, including symmetric and asymmetric
#' distance matrices, and can include or exclude within-run comparisons based on the RSA design.
#' @examples
#' dismat <- dist(matrix(rnorm(100*100), 100, 100))
#' rdes <- rsa_design(~ dismat, list(dismat=dismat))
#' rsa_model_mat(rdes)
#' @keywords internal
#' @noRd
rsa_model_mat <- function(rsa_des) {
  rvars <- labels(terms(rsa_des$formula))
  vset <- lapply(rvars, function(vname) {
    if (!(vname %in% names(rsa_des$data))) {
      stop("Variable '", vname, "' not found in RSA design data")
    }
    rsa_des$data[[vname]]
  })
  names(vset) <- rvars
  
  model_mat <- .rsa_design_vectorize_entries(vset, include = rsa_des$include)
  nuisance_mat <- .rsa_design_vectorize_entries(rsa_des$nuisance %||% list(),
                                                include = rsa_des$include)
  out <- c(model_mat, nuisance_mat)
  if (anyDuplicated(names(out))) {
    stop("Sanitized model/nuisance predictor names must be unique.",
         call. = FALSE)
  }
  out
}


#' @keywords internal
#' @noRd
run_rfit <- function(dvec, obj) {
  require_package("Rfit", "for robust regression in RSA")
  form <- paste("dvec", "~", paste(names(obj$design$model_mat), collapse = " + "))
  obj$design$model_mat$dvec <- dvec
  res <- Rfit::rfit(form, data=obj$design$model_mat)
  coef(res)[-1]
}


#' @keywords internal
#' @importFrom stats coef cor dist rnorm terms lm sd
#' @noRd
check_collinearity <- function(model_mat) {
  # Get the design matrix and names
  vnames <- names(model_mat)
  design_matrix <- as.matrix(model_mat)
  
  # Basic check - need at least 2 columns for collinearity
  if (ncol(design_matrix) > 1) {
    # Calculate correlation matrix and check for high correlations
    tryCatch({
      cor_matrix <- cor(design_matrix, use = "pairwise.complete.obs")
      diag(cor_matrix) <- 0
      if (any(abs(cor_matrix) > 0.99, na.rm = TRUE)) {
        high_cor_pairs <- which(abs(cor_matrix) > 0.99, arr.ind = TRUE)
        if (nrow(high_cor_pairs) > 0) {
          problem_vars <- apply(high_cor_pairs, 1, function(idx) {
            paste(vnames[c(idx[1], idx[2])], collapse = " and ")
          })
          stop(sprintf("Collinearity detected among predictors: %s. Consider removing one of the correlated variables.",
                       paste(problem_vars, collapse = "; ")))
        }
      }
      
      # Also check linear dependencies using QR decomposition
      qr_result <- qr(design_matrix)
      if (qr_result$rank < ncol(design_matrix)) {
        stop(sprintf("Design matrix is rank deficient (rank %d < %d columns). Some predictors are linear combinations of others.", 
                     qr_result$rank, ncol(design_matrix)))
      }
    }, error = function(e) {
      if (grepl("NA/NaN/Inf", e$message)) {
        stop("Cannot compute correlations due to NA/NaN/Inf values in predictor variables.")
      } else {
        stop(paste("Error checking collinearity:", e$message))
      }
    })
  }
}


#' Diagnose the effective support of an RSA design
#'
#' Summarises how much information an RSA design can bring to bear on each
#' predictor RDM.  RDM entries are not independent observations: every item
#' enters \code{n_items - 1} pairs, so the \code{n_pairs} entries of a
#' vectorised RDM carry on the order of \code{n_items} independent pieces of
#' information rather than \code{n_pairs}.  A regression coefficient's variance
#' is inflated further by the predictor's collinearity with the others, its
#' variance inflation factor (VIF).  The ratio \code{n_items / VIF} is
#' reported per predictor as the effective number of items supporting that
#' predictor's unique contribution.  Values below 10 mark a predictor whose
#' coefficient will vary across ROIs largely through noise.  This is a
#' heuristic screen, not a test; it flags designs that cannot separate their
#' predictors, it does not certify those that can.
#'
#' With an explicit \code{pair_mask}, only items participating in retained pairs
#' count toward effective support. The full item universe is still used for
#' condition alignment and item permutations.
#'
#' For \code{\link{pair_rsa_design}} objects in between-domain mode the item
#' count is \code{n_a + n_b}, since each item of either set enters every pair
#' with the other set.
#'
#' @param design An \code{rsa_design} or \code{pair_rsa_design}.
#'
#' @return An object of class \code{rsa_design_diagnostics}: a list with
#'   \code{n_items}, \code{n_pairs} (after any within-block exclusion),
#'   \code{n_predictors}, \code{predictors}, \code{predictor_roles},
#'   \code{max_abs_cor} and \code{max_abs_cor_pair} (the most correlated pair
#'   of predictors), \code{vif} (named, \code{Inf} when the design matrix is
#'   singular, \code{NA} for a constant predictor), \code{items_per_predictor}
#'   (\code{n_items / vif}), and \code{threshold} (10).
#'   \code{unsupported_predictors} names predictors with fewer than two
#'   distinct finite values; their VIF and effective item count are \code{NA},
#'   including when the design contains only that predictor.
#'
#' @seealso \code{\link{rsa_model}}, which computes this at construction and
#'   warns when a model predictor falls below the threshold, and
#'   \code{\link{run_permutation_searchlight}} for inference that respects the
#'   item-level dependence.
#'
#' @examples
#' set.seed(1)
#' items <- 12
#' shared <- matrix(rnorm(items * 4), items, 4)
#' a <- dist(shared)
#' b <- dist(shared + matrix(rnorm(items * 4, sd = 0.3), items, 4))
#' des <- rsa_design(~ a + b, list(a = a, b = b))
#' rsa_design_diagnostics(des)
#'
#' @export
rsa_design_diagnostics <- function(design) {
  assert_that(inherits(design, "rsa_design"))
  model_mat <- design$model_mat
  if (is.null(model_mat) || length(model_mat) == 0L) {
    stop("The RSA design has no predictors in `model_mat`.", call. = FALSE)
  }

  X <- as.matrix(do.call(cbind, model_mat))
  storage.mode(X) <- "double"
  colnames(X) <- names(model_mat)
  p       <- ncol(X)
  n_pairs <- nrow(X)
  n_items <- .rsa_design_n_items(design)
  if (!is.null(design$pair_mask)) {
    pairs <- which(lower.tri(matrix(FALSE, n_items, n_items)), arr.ind = TRUE)
    n_items <- length(unique(as.vector(pairs[design$include, , drop = FALSE])))
  }

  # Check variation even for a single predictor. A constant (or missing)
  # column cannot acquire support merely because no other columns exist.
  has_variation <- vapply(seq_len(p), function(j) {
    x <- X[, j]
    x <- x[is.finite(x)]
    length(x) > 1L && any(x != x[1L])
  }, logical(1))
  vif         <- stats::setNames(ifelse(has_variation, 1, NA_real_), colnames(X))
  max_abs_cor <- NA_real_
  max_pair    <- c(NA_character_, NA_character_)

  if (p > 1L) {
    # pairwise.complete.obs keeps an NA cell in one RDM from blanking the
    # whole correlation matrix; a constant column is NA on its own diagonal.
    R   <- suppressWarnings(stats::cor(X, use = "pairwise.complete.obs"))
    off <- abs(R)
    diag(off) <- NA_real_
    if (any(is.finite(off))) {
      idx         <- which(off == max(off, na.rm = TRUE), arr.ind = TRUE)[1L, ]
      max_abs_cor <- off[idx[1L], idx[2L]]
      max_pair    <- colnames(X)[sort(idx)]
    }

    good  <- has_variation & is.finite(diag(R))
    vif[] <- NA_real_
    if (sum(good) == 1L) {
      vif[good] <- 1
    } else if (sum(good) > 1L) {
      inv <- tryCatch(solve(R[good, good, drop = FALSE]), error = function(e) NULL)
      vif[good] <- if (is.null(inv)) Inf else pmax(diag(inv), 1)
    }
  }

  structure(
    list(
      n_items             = n_items,
      n_pairs             = n_pairs,
      n_predictors        = p,
      predictors          = colnames(X),
      predictor_roles     = design$predictor_roles,
      unsupported_predictors = colnames(X)[!has_variation],
      max_abs_cor         = max_abs_cor,
      max_abs_cor_pair    = max_pair,
      vif                 = vif,
      items_per_predictor = n_items / vif,
      threshold           = .rsa_min_items_per_predictor
    ),
    class = "rsa_design_diagnostics"
  )
}

#' @export
print.rsa_design_diagnostics <- function(x, ...) {
  cat("RSA design diagnostics\n")
  cat(sprintf("  items: %d   pairs: %d   predictors: %d\n",
              x$n_items, x$n_pairs, x$n_predictors))
  if (is.finite(x$max_abs_cor)) {
    cat(sprintf("  max |r| between predictors: %.3f (%s, %s)\n",
                x$max_abs_cor, x$max_abs_cor_pair[1L], x$max_abs_cor_pair[2L]))
  }
  cat("  effective items per predictor (items / VIF):\n")
  for (nm in x$predictors) {
    ipp  <- x$items_per_predictor[[nm]]
    flag <- if (nm %in% x$unsupported_predictors) {
      "  <- no usable variation"
    } else if (is.finite(ipp) && ipp < x$threshold) {
      "  <- below threshold"
    } else {
      ""
    }
    cat(sprintf("    %-20s VIF %7.2f   ~%6.1f items%s\n", nm, x$vif[[nm]], ipp, flag))
  }
  invisible(x)
}

# Effective items per predictor below which rsa_model() warns for regression
# regtypes.  A heuristic; see rsa_design_diagnostics().
.rsa_min_items_per_predictor <- 10

#' @keywords internal
#' @noRd
.rsa_design_n_items <- function(design) {
  if (!is.null(design$n_a)) {
    if (identical(design$pair_kind %||% "within", "between")) {
      return(as.integer(design$n_a + design$n_b))
    }
    return(as.integer(design$n_a))
  }
  if (!is.null(design$data) && length(design$data) > 0L) {
    return(as.integer(.rsa_design_entry_size(design$data[[1L]])))
  }
  if (is.null(design$include) && length(design$model_mat) > 0L) {
    len <- length(design$model_mat[[1L]])
    n   <- (1 + sqrt(1 + 8 * len)) / 2
    if (isTRUE(all.equal(n, round(n)))) return(as.integer(round(n)))
  }
  stop("Cannot determine the number of items in this RSA design.", call. = FALSE)
}

#' @keywords internal
#' @noRd
.rsa_warn_effective_support <- function(diagnostics, design) {
  preds <- design$model_predictors
  if (is.null(preds) || length(preds) == 0L) {
    preds <- names(diagnostics$items_per_predictor)
  }
  unsupported <- intersect(preds, diagnostics$unsupported_predictors)
  if (length(unsupported) > 0L) {
    warning(sprintf(
      "RSA predictor(s) '%s' have no usable variation (fewer than two distinct finite values); their coefficients are not identifiable and effective support is NA.",
      paste(unsupported, collapse = "', '")
    ), call. = FALSE)
  }
  ipp <- diagnostics$items_per_predictor[intersect(preds, names(diagnostics$items_per_predictor))]
  ipp <- ipp[is.finite(ipp)]
  if (length(ipp) == 0L || min(ipp) >= diagnostics$threshold) {
    return(invisible(FALSE))
  }
  worst    <- names(ipp)[which.min(ipp)]
  vif_w    <- diagnostics$vif[[worst]]
  shared   <- sprintf(paste0(
    "RDM entries share items, so the %d pairs carry roughly %d independent ",
    "observations. Per-ROI t-values overstate the evidence. See ",
    "run_permutation_searchlight() for the supported RSA null hypotheses; ",
    "conditional coefficient inference with other predictors is not implemented."),
    diagnostics$n_pairs, diagnostics$n_items)

  msg <- if (vif_w < 1.5) {
    # Item-limited: collinearity is not the problem, the item count is.
    sprintf(paste0(
      "RSA design has only %d items, which is ~%.1f effective items for predictor ",
      "'%s' (VIF = %.1f). Its coefficient will be unstable across ROIs. Add items ",
      "or pool runs. %s"),
      diagnostics$n_items, ipp[[worst]], worst, vif_w, shared)
  } else {
    cor_txt <- if (is.finite(diagnostics$max_abs_cor)) {
      sprintf("; max |r| between predictors = %.2f (%s vs %s)",
              diagnostics$max_abs_cor,
              diagnostics$max_abs_cor_pair[1L], diagnostics$max_abs_cor_pair[2L])
    } else {
      ""
    }
    sprintf(paste0(
      "RSA design supports predictor '%s' with only ~%.1f effective items ",
      "(%d items, VIF = %.1f%s). Variance inflation from collinear predictors ",
      "divides the item count further, and the coefficient will be unstable ",
      "across ROIs. Use fewer or less collinear predictors. %s"),
      worst, ipp[[worst]], diagnostics$n_items, vif_w, cor_txt, shared)
  }
  warning(msg, call. = FALSE)
  invisible(TRUE)
}

#' @keywords internal
#' @noRd
.rsa_apply_item_perm <- function(idx, perm, what = "item_perm") {
  if (is.null(perm)) return(idx)
  n <- length(idx)
  if (length(perm) != n || !identical(sort(as.integer(perm)), seq_len(n))) {
    stop(sprintf("`%s` must be a permutation of 1..%d (length %d supplied).",
                 what, n, length(perm)), call. = FALSE)
  }
  idx[perm]
}


#' @keywords internal
#' @importFrom stats coef cor dist rnorm terms lm sd
#' @noRd
run_lm <- function(dvec, obj) {
  # This is the standard LM approach that returns T-values for each predictor.
  form <- paste("dvec", "~", paste(names(obj$design$model_mat), collapse = " + "))
  vnames <- names(obj$design$model_mat)
  obj$design$model_mat$dvec <- dvec
  
  fit <- lm(form, data=obj$design$model_mat)
  # Return T-values (3rd column of coef summary)
  tvals <- coef(summary(fit))[-1, 3]
  names(tvals) <- vnames
  tvals
}


#' @keywords internal
#' @noRd
run_cor <- function(dvec, obj) {
  # For 'pearson' or 'spearman' regtype, we just do correlation with each predictor
  res <- sapply(obj$design$model_mat, function(x) cor(dvec, x, method=if (identical(obj$distmethod, "crossvalidated_euclidean")) obj$regtype else obj$distmethod))
  names(res) <- names(obj$design$model_mat)
  res
}

.rsa_fast_kernel_enabled <- function() {
  .fast_path_enabled("rsa_fast_kernel")
}

.rsa_prepare_fast_kernel <- function(design, regtype, distmethod, semipartial, nneg) {
  model_mat <- design$model_mat
  if (is.null(model_mat) || length(model_mat) == 0L) {
    return(NULL)
  }

  X <- do.call(cbind, model_mat)
  if (!is.matrix(X) || nrow(X) == 0L || ncol(X) == 0L) {
    return(NULL)
  }
  X <- as.matrix(X)
  storage.mode(X) <- "double"

  var_names <- colnames(X)
  if (is.null(var_names) || any(!nzchar(var_names))) {
    var_names <- names(model_mat)
  }
  if (is.null(var_names) || length(var_names) != ncol(X)) {
    var_names <- paste0("V", seq_len(ncol(X)))
  }
  colnames(X) <- var_names

  state <- list(cor = NULL, lm = NULL)

  if (regtype %in% c("pearson", "spearman")) {
    X_cor <- if (identical(distmethod, "spearman")) {
      apply(X, 2, rank, ties.method = "average")
    } else {
      X
    }
    X_cor <- as.matrix(X_cor)
    storage.mode(X_cor) <- "double"
    colnames(X_cor) <- var_names

    X_center <- sweep(X_cor, 2, colMeans(X_cor), FUN = "-")
    x_ss <- colSums(X_center^2)

    state$cor <- list(
      X_center = X_center,
      x_ss = x_ss,
      var_names = var_names,
      method = distmethod
    )
  }

  can_fast_lm <- identical(regtype, "lm") && (is.null(nneg) || length(nneg) == 0L) && !isTRUE(semipartial)
  if (can_fast_lm) {
    X_with_intercept <- cbind(`(Intercept)` = 1, X)
    df <- nrow(X_with_intercept) - ncol(X_with_intercept)

    if (df > 0L) {
      XtX <- crossprod(X_with_intercept)
      XtX_chol <- tryCatch(chol(XtX), error = function(e) NULL)
      if (!is.null(XtX_chol)) {
        XtX_inv <- chol2inv(XtX_chol)
        state$lm <- list(
          X_with_intercept = X_with_intercept,
          XtX_inv = XtX_inv,
          diag_xtx_inv = diag(XtX_inv),
          df = df,
          var_names = var_names
        )
      }
    }
  }

  if (is.null(state$cor) && is.null(state$lm)) {
    return(NULL)
  }
  state
}

run_cor_fast <- function(dvec, obj) {
  state <- obj$.fast_kernel$cor
  if (is.null(state)) {
    return(run_cor(dvec, obj))
  }

  dwork <- if (identical(state$method, "spearman")) {
    # Identical to rank(dvec, ties.method = "average"), with less overhead.
    as.vector(matrixStats::colRanks(matrix(as.numeric(dvec)), ties.method = "average",
                                    preserveShape = TRUE))
  } else {
    dvec
  }
  dwork <- as.numeric(dwork)

  d_center <- dwork - mean(dwork)
  d_ss <- sum(d_center^2)
  out <- rep(NA_real_, length(state$var_names))

  if (is.finite(d_ss) && d_ss > 0) {
    numer <- drop(crossprod(state$X_center, d_center))
    denom <- sqrt(state$x_ss * d_ss)
    keep <- is.finite(denom) & denom > 0
    out[keep] <- numer[keep] / denom[keep]
  }

  names(out) <- state$var_names
  out
}

run_lm_fast <- function(dvec, obj) {
  state <- obj$.fast_kernel$lm
  if (is.null(state)) {
    return(run_lm(dvec, obj))
  }

  y <- as.numeric(dvec)
  if (!all(is.finite(y))) {
    return(run_lm(dvec, obj))
  }
  xty <- drop(crossprod(state$X_with_intercept, y))
  beta <- drop(state$XtX_inv %*% xty)
  residual <- y - drop(state$X_with_intercept %*% beta)
  sigma2 <- sum(residual^2) / state$df
  if (!is.finite(sigma2) || sigma2 < 0) {
    return(run_lm(dvec, obj))
  }

  se <- sqrt(state$diag_xtx_inv * sigma2)
  tvals <- beta[-1] / se[-1]
  names(tvals) <- state$var_names
  tvals
}

# QR compilation keeps coefficient queries separate from pair-based t-values.
# Missing neural cells change the eligible design, so their queries are rebuilt.
.rsa_coefficient_query <- function(model_mat, model_names, contrasts = NULL, rows = NULL,
                                   validate_only = FALSE) {
  X <- cbind(`(Intercept)` = 1, do.call(cbind, model_mat))
  storage.mode(X) <- "double"
  if (is.null(rows)) rows <- seq_len(nrow(X))
  rows <- rows[apply(X[rows, , drop = FALSE], 1L, function(x) all(is.finite(x)))]
  Xk <- X[rows, , drop = FALSE]
  decomposition <- if (length(rows)) qr(Xk) else NULL
  if (!length(rows) || decomposition$rank < ncol(X)) {
    aliases <- if (length(rows)) {
      colnames(X)[decomposition$pivot[seq.int(decomposition$rank + 1L, ncol(X))]]
    } else colnames(X)
    stop("Relational coefficient design is rank deficient including its intercept; ",
         "aliased or unsupported columns: ", paste(aliases, collapse = ", "),
         ". Check background terms and eligible pairs.", call. = FALSE)
  }
  if (isTRUE(validate_only)) return(invisible(NULL))
  operator <- backsolve(qr.R(decomposition), t(qr.Q(decomposition)))
  operator <- operator[order(decomposition$pivot), , drop = FALSE]
  rownames(operator) <- colnames(X)
  query <- operator[model_names, , drop = FALSE]
  if (length(contrasts)) {
    if (!is.list(contrasts) || is.null(names(contrasts)) || anyNA(names(contrasts)) ||
        any(!nzchar(names(contrasts))) || anyDuplicated(names(contrasts))) {
      stop("`contrasts` must be a uniquely named list of named numeric coefficient weights.",
           call. = FALSE)
    }
    for (nm in names(contrasts)) {
      weights <- contrasts[[nm]]
      if (!is.numeric(weights) || !length(weights) || any(!is.finite(weights)) ||
          is.null(names(weights)) || anyNA(names(weights)) || any(!nzchar(names(weights))) ||
          anyDuplicated(names(weights)) || any(!names(weights) %in% colnames(X))) {
        stop("Contrast '", nm, "' must contain finite named weights for design coefficients.",
             call. = FALSE)
      }
      value <- matrix(drop(crossprod(weights, operator[names(weights), , drop = FALSE])),
                      nrow = 1L)
      rownames(value) <- paste0("contrast_", nm)
      query <- rbind(query, value)
    }
  }
  if (anyDuplicated(rownames(query))) {
    stop("Contrast output names must not duplicate model predictor names.", call. = FALSE)
  }
  if (!nrow(query)) {
    stop("Coefficient output requires model predictors or a requested contrast.", call. = FALSE)
  }
  list(query = query, rows = rows)
}

.rsa_coefficient_metrics <- function(y, obj) {
  state <- obj$.coefficient_query
  if (is.null(state) || any(!is.finite(y[state$rows]))) {
    state <- .rsa_coefficient_query(obj$design$model_mat, obj$design$model_predictors,
                                    obj$contrasts, rows = which(is.finite(y)))
  }
  out <- drop(state$query %*% y[state$rows])
  stats::setNames(as.numeric(out), rownames(state$query))
}

# Correlations are bilinear after row-wise centering/ranking and normalization.
# Contract fixed coefficient queries directly with the patterns, avoiding the
# neural pair matrix. Non-finite/degenerate patterns use the ordinary fallback.
.rsa_coefficient_contraction <- function(A, B, obj, between) {
  state <- obj$.coefficient_query
  if (is.null(state) || !all(is.finite(A)) || !all(is.finite(B))) return(NULL)
  left <- .era_normalize_similarity_rows(A, obj$distmethod)
  right <- .era_normalize_similarity_rows(B, obj$distmethod)
  if (!all(left$valid) || !all(right$valid)) return(NULL)
  n_pairs <- if (between) nrow(A) * nrow(B) else choose(nrow(A), 2L)
  eligible <- if (is.null(obj$design$include)) seq_len(n_pairs) else which(obj$design$include)
  out <- vapply(seq_len(nrow(state$query)), function(k) {
    weights <- numeric(n_pairs)
    weights[eligible[state$rows]] <- state$query[k, ]
    Q <- matrix(0, nrow(A), nrow(B))
    if (between) Q[] <- weights else Q[lower.tri(Q)] <- weights
    value <- sum((t(Q) %*% left$values) * right$values)
    if (identical(obj$measure, "similarity")) value else sum(weights) - value
  }, numeric(1L))
  stats::setNames(out, rownames(state$query))
}


################################################################################
# NEW: Constrained LM with glmnet
################################################################################
#' @keywords internal
#' @importFrom stats predict
#' @noRd
run_lm_constrained <- function(dvec, obj) {
  require_package("glmnet", "for non-negative constrained regression in RSA")
  
  # Convert list of vectors (predictors) into a matrix
  var_names <- names(obj$design$model_mat)
  X <- do.call(cbind, obj$design$model_mat)  # columns = predictors
  colnames(X) <- var_names
  
  # Identify which predictors should be constrained to be >= 0
  if (is.null(obj$nneg)) {
    stop("run_lm_constrained called, but obj$nneg is NULL.")
  }
  
  nneg_names <- names(obj$nneg)
  lower_lim_vec <- sapply(var_names, function(vn) {
    if (vn %in% nneg_names) 0 else -Inf
  })
  
  # Create penalty_factor vector - add a small penalty to non-negative terms
  # and zero penalty to unconstrained terms to avoid the "all penalty factors <= 0" error
  penalty_factor <- sapply(var_names, function(vn) {
    if (vn %in% nneg_names) 1e-5 else 0
  })
  
  # Use a small alpha (mixing parameter) to ensure stability
  alpha_val <- 1e-5
  
  # Fit glmnet with near-zero lambda and minimal penalty on non-negative variables
  fit <- tryCatch({
    glmnet::glmnet(
      x = X,
      y = dvec,
      alpha = alpha_val,                       
      lambda = 1e-5,                  
      penalty.factor = penalty_factor,
      lower.limits = lower_lim_vec,
      standardize = FALSE,
      intercept = TRUE
    )
  }, error = function(e) {
    # If error still occurs, try a different approach with all penalty factors = 1
    warning("First glmnet attempt failed, trying with uniform penalties: ", e$message)
    glmnet::glmnet(
      x = X,
      y = dvec,
      alpha = alpha_val,
      lambda = 1e-5,
      lower.limits = lower_lim_vec,
      standardize = FALSE,
      intercept = TRUE
    )
  })
  
  # Extract coefficients at smallest lambda
  lambda_min <- min(fit$lambda)
  
  # Properly extract coefficients - coef is S3 method
  coef_matrix <- predict(fit, type = "coefficients", s = lambda_min)
  # First row is intercept, we want rows 2:end
  betas <- as.numeric(coef_matrix)[-1]
  names(betas) <- var_names
  
  betas
}


################################################################################
# NEW: Semi-Partial LM
################################################################################
#' @keywords internal
#' @noRd
run_lm_semipartial <- function(dvec, obj) {
  # Compute semi-partial correlations from a single LM fit
  # sr_i = sign(t_i) * sqrt( (t_i^2 * MSE) / TSS )
  
  form <- paste("dvec", "~", paste(names(obj$design$model_mat), collapse = " + "))
  vnames <- names(obj$design$model_mat)
  obj$design$model_mat$dvec <- dvec
  
  fit  <- lm(form, data=obj$design$model_mat)
  smry <- summary(fit)
  
  # summary.lm omits aliased coefficients from its coefficient table. Keep the
  # design contract stable by filling only estimable terms into a full vector.
  coefficient_table <- coef(smry)
  tvals <- setNames(rep(NA_real_, length(vnames)), vnames)
  estimable <- intersect(vnames, rownames(coefficient_table))
  tvals[estimable] <- coefficient_table[estimable, "t value"]
  
  # Residual MSE
  MSE <- smry$sigma^2
  
  # TSS = total sum of squares of the outcome
  y_mod <- fit$model$dvec
  TSS   <- sum((y_mod - mean(y_mod))^2)
  
  # Compute sr_i
  sr2 <- (tvals^2 * MSE) / TSS
  sr  <- sign(tvals) * sqrt(sr2)
  
  sr
}


################################################################################
# TRAINING METHOD
################################################################################
#' @rdname train_model
#' @param obj An object of class \code{rsa_model}.
#' @param train_dat The training data.
#' @param y The response variable.
#' @param indices The indices of the training data.
#' @param ... Additional arguments passed to the training method.
#' @return
#' Depending on \code{obj$regtype}:
#' \itemize{
#'   \item \code{"lm"} + no constraints + \code{obj$semipartial=TRUE}: semi-partial correlations
#'   \item \code{"lm"} + no constraints + \code{obj$semipartial=FALSE}: T-values of each predictor
#'   \item \code{"lm"} + \code{nneg} constraints: raw coefficients from constrained \code{glmnet}
#'   \item \code{"rfit"}: robust regression coefficients
#'   \item \code{"pearson"} or \code{"spearman"}: correlation coefficients
#' }
#' @method train_model rsa_model
#' @export
train_model.rsa_model <- function(obj, train_dat, y, indices, ...) {
  use_fast_kernel <- !is.null(obj$.fast_kernel)

  pair_kind <- if (!is.null(obj$design$pair_kind)) obj$design$pair_kind else "within"

  # 1) correlation-based distance, branched on pair geometry
  train_dat <- center_patterns(train_dat, method = obj$pattern_center %||% "none")

  if (identical(obj$distmethod, "crossvalidated_euclidean")) {
    dvec <- .rsa_crossvalidated_response(obj, train_dat)
  } else if (identical(pair_kind, "between")) {
    ia <- obj$design$row_idx_a
    ib <- obj$design$row_idx_b
    if (is.null(ia) || is.null(ib)) {
      stop("pair_kind='between' requires `row_idx_a` and `row_idx_b` in the design.",
           call. = FALSE)
    }
    if (max(c(ia, ib)) > nrow(train_dat) || min(c(ia, ib)) < 1L) {
      stop("`row_idx_a`/`row_idx_b` reference rows outside the training data.",
           call. = FALSE)
    }
    # Permutation-test hook (see permute_labels.pair_rsa_design): relabel the
    # neural patterns of each item set within its own blocks.
    ia <- .rsa_apply_item_perm(ia, obj$design$item_perm, "item_perm")
    ib <- .rsa_apply_item_perm(ib, obj$design$item_perm_b, "item_perm_b")
    if (identical(obj$statistic, "beta") && !isTRUE(obj$return_fingerprint)) {
      result <- .rsa_coefficient_contraction(train_dat[ia, , drop = FALSE],
                                             train_dat[ib, , drop = FALSE], obj, TRUE)
      if (!is.null(result)) return(result)
    }
    M <- 1 - stats::cor(t(train_dat[ia, , drop = FALSE]),
                         t(train_dat[ib, , drop = FALSE]),
                         method = obj$distmethod)
    dvec <- as.vector(M)
  } else {
    ia <- obj$design$row_idx_a
    if (!is.null(ia)) {
      if (max(ia) > nrow(train_dat) || min(ia) < 1L) {
        stop("`row_idx_a` references rows outside the training data.",
             call. = FALSE)
      }
      train_dat <- train_dat[ia, , drop = FALSE]
    }
    # Permutation-test hook (see permute_labels.rsa_design): relabel items by
    # permuting pattern rows, equivalent to permuting every model RDM by the
    # inverse permutation while leaving the model matrix and kernel cached.
    if (!is.null(obj$design$item_perm)) {
      rows      <- .rsa_apply_item_perm(seq_len(nrow(train_dat)), obj$design$item_perm)
      train_dat <- train_dat[rows, , drop = FALSE]
    }
    if (identical(obj$statistic, "beta") && !isTRUE(obj$return_fingerprint)) {
      result <- .rsa_coefficient_contraction(train_dat, train_dat, obj, FALSE)
      if (!is.null(result)) return(result)
    }
    if (identical(obj$statistic, "beta")) {
      # Match the rectangular measurement rule. In particular, cor() keeps
      # missing observations missing when ranking for Spearman correlation.
      similarity <- stats::cor(t(train_dat), method = obj$distmethod)
      dvec <- 1 - similarity[lower.tri(similarity)]
    } else {
      dvec <- .rdm_vector_correlation(train_dat, method = obj$distmethod, center = "none")
    }
  }

  # 2) Exclude certain comparisons if needed
  if (!is.null(obj$design$include)) {
    dvec <- dvec[obj$design$include]
  }

  if (identical(obj$measure, "similarity")) dvec <- 1 - dvec

  # 3) Switch on regtype + constraints + semipartial
  out <- switch(
    obj$regtype,

    # robust regression
    rfit = run_rfit(dvec, obj),

    # linear model
    lm = {
      if (identical(obj$statistic, "beta")) {
        .rsa_coefficient_metrics(dvec, obj)
      } else {
        has_nneg <- (!is.null(obj$nneg) && length(obj$nneg) > 0)

        if (has_nneg) {
          # Use constrained approach
          run_lm_constrained(dvec, obj)
        } else if (isTRUE(obj$semipartial)) {
          # Semi-partial correlations
          run_lm_semipartial(dvec, obj)
        } else if (use_fast_kernel && !is.null(obj$.fast_kernel$lm)) {
          run_lm_fast(dvec, obj)
        } else {
          # Standard approach = t-values
          run_lm(dvec, obj)
        }
      }
    },

    # correlation-based
    pearson  = if (use_fast_kernel && !is.null(obj$.fast_kernel$cor)) run_cor_fast(dvec, obj) else run_cor(dvec, obj),
    spearman = if (use_fast_kernel && !is.null(obj$.fast_kernel$cor)) run_cor_fast(dvec, obj) else run_cor(dvec, obj)
  )

  if (isTRUE(obj$return_fingerprint) && !is.null(obj$.fingerprint_basis)) {
    out <- .rsa_attach_fingerprint(out, dvec, obj$.fingerprint_basis)
  }

  out
}


#' Merge Results for RSA Model
#'
#' This function takes the computed coefficients/correlations/t-values 
#' from \code{train_model.rsa_model} for a single ROI/searchlight and formats 
#' it into the standard output tibble.
#'
#' @param obj The RSA model specification.
#' @param result_set A tibble containing the results from the processor function for the current ROI/sphere. 
#'   Expected to have a \code{$result} column containing the named vector from \code{train_model.rsa_model}.
#' @param indices Voxel indices for the current ROI/searchlight sphere.
#' @param id Identifier for the current ROI/searchlight center.
#' @param ... Additional arguments (ignored).
#'
#' @return A tibble row with the formatted "performance" metrics (coefficients/t-values/correlations) for the ROI/sphere.
#' @importFrom tibble tibble
#' @importFrom futile.logger flog.error
#' @rdname merge_results-methods
#' @method merge_results rsa_model
#' @export
merge_results.rsa_model <- function(obj, result_set, indices, id, ...) {
  
  # Check for errors from previous steps (processor/train_model)
  if (any(result_set$error)) {
    emessage <- result_set$error_message[which(result_set$error)[1]]
    # Return standard error tibble structure
    return(
      tibble::tibble(
        result       = list(NULL),
        indices      = list(indices),
        performance  = list(NULL),
        id           = id,
        error        = TRUE,
        error_message= emessage,
        fingerprint  = list(NULL)
      )
    )
  }
  
  # Extract the model outputs (named vector) computed by train_model.
  if (!"result" %in% names(result_set) || length(result_set$result) == 0 || is.null(result_set$result[[1]])) {
     error_msg <- sprintf("merge_results (rsa_model): result_set missing or has NULL/empty 'result' field where model outputs were expected for ROI/ID %s.", id)
     futile.logger::flog.error(error_msg)
     
     # Create NA performance matrix based on expected names from the design
     expected_names <- names(obj$design$model_mat)
     perf_mat <- matrix(NA_real_, nrow=1, ncol=length(expected_names), dimnames=list(NULL, expected_names))
     if (length(expected_names) == 0) perf_mat <- NULL 
     
     return(tibble::tibble(result=list(NULL), indices=list(indices), performance=list(perf_mat),
                           id=id, error=TRUE, error_message=error_msg,
                           fingerprint=list(NULL)))
  }
  
  model_outputs <- result_set$result[[1]]
  fingerprint   <- attr(model_outputs, "fingerprint", exact = TRUE)

  # Validate the extracted results
  if (!is.numeric(model_outputs) || is.null(names(model_outputs)) || length(model_outputs) == 0) {
      error_msg <- sprintf("merge_results (rsa_model): Extracted model outputs are not a named non-empty numeric vector for ROI/ID %s.", id)
      futile.logger::flog.error(error_msg)

      # Attempt to use names from model_outputs if partially valid, otherwise from design
      current_names <- names(model_outputs)
      if (is.null(current_names) || length(current_names) == 0) {
        current_names <- names(obj$design$model_mat)
      }

      perf_mat <- matrix(NA_real_, nrow=1, ncol=length(current_names), dimnames=list(NULL, current_names))
      if (length(current_names) == 0) perf_mat <- NULL

      return(tibble::tibble(result=list(NULL), indices=list(indices), performance=list(perf_mat),
                            id=id, error=TRUE, error_message=error_msg,
                            fingerprint=list(NULL)))
  }

  # Strip the fingerprint attribute before forming the performance matrix
  attributes(model_outputs)[["fingerprint"]] <- NULL

  # Format the results into a 1-row matrix (performance matrix)
  perf_mat <- matrix(model_outputs, nrow = 1, dimnames = list(NULL, names(model_outputs)))

  # Return the standard tibble structure
  tibble::tibble(
    result      = list(NULL), # Model outputs are now in 'performance'
    indices     = list(indices),
    performance = list(perf_mat),
    id          = id,
    error       = FALSE,
    error_message = "~",
    fingerprint = list(fingerprint)
  )
}


#' @rdname fit_roi
#' @method fit_roi rsa_model
#' @export
fit_roi.rsa_model <- function(model, roi_data, context, ...) {
  train_dat <- roi_data$train_data
  fit_error <- NULL

  result <- tryCatch(
    train_model(model, train_dat, y = NULL, indices = roi_data$indices),
    error = function(e) {
      fit_error <<- conditionMessage(e)
      NULL
    }
  )

  if (is.null(result) || !is.numeric(result) || length(result) == 0) {
    return(roi_result(
      metrics = NULL,
      indices = roi_data$indices,
      id = context$id,
      error = TRUE,
      error_message = paste0(sprintf("rsa_model: train_model failed for ROI %s", context$id),
                             if (!is.null(fit_error)) paste0(": ", fit_error))
    ))
  }

  roi_result(
    metrics = result,
    indices = roi_data$indices,
    id = context$id
  )
}

#' @export
#' @method y_train rsa_model
y_train.rsa_model <- function(obj) {
  obj$condition_labels
}

################################################################################
# PRINT METHODS
################################################################################
#' @export
#' @method print rsa_model
print.rsa_model <- function(x, ...) {
  # Print header
  cat("\n", "RSA Model", "\n")
  cat(rep("-", 20), "\n\n")

  # Model configuration
  cat("Configuration:\n")
  cat("  |- Distance Method: ", x$distmethod, "\n")
  cat("  |- Regression Type: ", x$regtype, "\n")
  if (identical(x$measure, "similarity")) cat("  |- Measurement: correlation similarity\n")
  if (identical(x$statistic, "beta")) cat("  |- Output: model coefficients and requested contrasts\n")

  # If nonneg constraints are present
  if (!is.null(x$nneg) && length(x$nneg) > 0) {
    cat("  |- Non-negativity on: ", paste(names(x$nneg), collapse=", "), "\n")
  }

  # If semipartial
  if (isTRUE(x$semipartial) && (is.null(x$nneg) || length(x$nneg) == 0)) {
    cat("  |- Semi-partial: TRUE\n")
  }
  cat("\n")

  # Dataset info
  cat("Dataset:\n")
  dims <- dim(x$dataset$train_data)
  dim_str <- paste0(
    paste(dims[-length(dims)], collapse=" x "),
    " x ", dims[length(dims)], " observations"
  )
  cat("  |- Dimensions: ", dim_str, "\n")
  cat("  |- Type: ", class(x$dataset$train_data)[1], "\n")
  cat("\n")

  # Design info
  cat("Design:\n")
  cat("  |- Formula: ", deparse(x$design$formula), "\n")

  var_names <- names(x$design$model_mat)
  cat("  |- Predictors: ", paste(var_names, collapse=", "), "\n")
  if (!is.null(x$design_diagnostics)) {
    d <- x$design_diagnostics
    cat("  |- Items: ", d$n_items, "   Pairs: ", d$n_pairs, "\n", sep = "")
    if (is.finite(d$max_abs_cor)) {
      cat(sprintf("  |- Max |r| between predictors: %.3f (%s, %s)\n",
                  d$max_abs_cor, d$max_abs_cor_pair[1L], d$max_abs_cor_pair[2L]))
    }
    ipp <- d$items_per_predictor
    cat("  |- Effective items per predictor (items / VIF): ",
        paste(sprintf("%s = %.1f", names(ipp), ipp), collapse = ", "), "\n", sep = "")
  }
  cat("\n")

  # Structure info
  cat("Structure:\n")

  # Block info
  if (!is.null(x$design$block_var)) {
    blocks <- table(x$design$block_var)
    cat("  |- Blocking: Present\n")
    cat("  |- Number of Blocks: ", length(blocks), "\n")
    cat("  |- Mean Block Size: ",
        format(mean(blocks), digits=2),
        " (SD: ",
        format(sd(blocks), digits=2),
        ")\n")
  } else {
    cat("  |- Blocking: None\n")
  }

  # Split info
  if (!is.null(x$design$split_by)) {
    split_info <- length(x$design$split_groups)
    cat("  |- Split Groups: ", split_info, "\n")
  } else {
    cat("  |- Split Groups: None\n")
  }

  cat("\n")
}


#' @export
#' @method print rsa_design
print.rsa_design <- function(x, ...) {
  # Print header
  cat("\n", "RSA Design", "\n")
  cat(rep("-", 20), "\n\n")

  # Formula
  cat("Formula:\n")
  cat("  |- ", deparse(x$formula), "\n\n")

  # Variables
  cat("Variables:\n")
  var_types <- sapply(x$data, function(v) {
    if (inherits(v, "dist")) "distance matrix"
    else if (is.matrix(v)) "matrix"
    else if (is.vector(v)) "vector"
    else "other"
  })

  cat("  |- Total Variables: ", length(x$data), "\n")
  for (i in seq_along(x$data)) {
    prefix <- if (i == length(x$data)) "  |-" else "  |-"
    cat(sprintf("%s %s: %s\n", prefix, names(x$data)[i], var_types[i]))
  }
  cat("\n")

  # Structure
  cat("Structure:\n")

  # Block info
  if (!is.null(x$block_var)) {
    blocks <- table(x$block_var)
    cat("  |- Blocking: Present\n")
    cat("  |- Number of Blocks: ", length(blocks), "\n")
    cat("  |- Block Sizes: ",
        paste0(names(blocks), ": ", blocks, collapse=", "), "\n")
  } else {
    cat("  |- Blocking: None\n")
  }

  # Include/exclude info
  if (!is.null(x$include)) {
    n_comparisons <- length(x$include)
    n_included <- sum(x$include)
    cat("  |- Comparisons: ",
        n_included,
        " of ",
        n_comparisons,
        sprintf(" (%.1f%%)", 100*n_included/n_comparisons), "\n")
  } else {
    cat("  |- Comparisons: All included\n")
  }

  cat("\n")
}


#' Construct an RSA (Representational Similarity Analysis) model
#'
#' This function creates an RSA model object by taking an MVPA (Multi-Variate Pattern Analysis) dataset and an RSA design.
#'
#' @seealso \code{\link{rsa_neural_rdm}} to compute the full neural correlation
#'   distance matrix from supplied observation-by-feature patterns.
#'
#' @param dataset An instance of an \code{mvpa_dataset}.
#' @param design An instance of an \code{rsa_design} created by \code{rsa_design()}.
#' @param distmethod A character string specifying the method used to compute distances between observations. 
#'        One of: \code{"pearson"}, \code{"spearman"} (default), or
#'        \code{"crossvalidated_euclidean"} (see below).
#' @param regtype A character string specifying the analysis method. 
#'        One of: \code{"pearson"}, \code{"spearman"}, \code{"lm"}, or \code{"rfit"} (defaults to "pearson").
#' @param check_collinearity Logical. When \code{regtype = "lm"}, stop if two
#'   predictor RDMs correlate above 0.99 or the design matrix is rank deficient.
#'   When \code{regtype} is \code{"lm"} or \code{"rfit"}, also warn if a model
#'   predictor has no usable variation or fewer than 10 effective items (see the section
#'   on effective support). Default is TRUE.
#' @param nneg A named list of variables (predictors) for which non-negative regression coefficients should be enforced 
#'        (only if \code{regtype="lm"}). Defaults to \code{NULL} (no constraints).
#' @param semipartial Logical indicating whether to compute semi-partial correlations in the \code{"lm"} case 
#'        (only if \code{nneg} is not used). Defaults to \code{FALSE}.
#' @param pattern_center Optional pattern-centering method applied to the stimulus-by-voxel matrix
#'   before distances are computed. Use \code{"stimulus_mean"} to subtract the across-stimulus
#'   mean pattern (Hanson-style). Default is \code{"none"}.
#' @param return_fingerprint Logical; if \code{TRUE}, project the per-unit
#'   neural pair-dissimilarity vector onto an orthonormal basis of the signal
#'   model RDM subspace and return the standardized model-space score vector
#'   alongside the standard outputs. For \code{\link{pair_rsa_design}} objects,
#'   predictors supplied through \code{nuisance} are excluded from this
#'   fingerprint basis. The basis is cached on the model spec and reused
#'   across ROIs/searchlight units. Default \code{FALSE}.
#' @param fingerprint_method Standardization method used when
#'   \code{return_fingerprint = TRUE}. One of \code{"pearson"} (centered/scaled)
#'   or \code{"spearman"} (rank-then-standardize). Default \code{"pearson"}.
#' @param fingerprint_basis Basis used to span the model RDM subspace when
#'   \code{return_fingerprint = TRUE}: \code{"pca"} (default) or \code{"qr"}.
#' @param measure Neural pair measurement: \code{"distance"} (default,
#'   correlation distance) or \code{"similarity"} (correlation). The choice
#'   applies after pattern centering and uses \code{distmethod} in either case.
#' @param statistic \code{NULL} preserves the existing output selected by
#'   \code{regtype}/\code{semipartial}. Use \code{"beta"} with ordinary,
#'   unconstrained \code{regtype = "lm"} to return raw model coefficients.
#'   Nuisance coefficients remain internal. Fixed designs cache QR coefficient
#'   queries; missing neural cells rebuild the query for eligible pairs.
#' @param contrasts Optional uniquely named list of named numeric coefficient
#'   weights, available with \code{statistic = "beta"}. Coefficient names are
#'   those in \code{design$model_mat}, plus \code{"(Intercept)"}. Outputs are
#'   named \code{contrast_<name>}.
#'
#' @param condition_labels Observation-aligned vector of condition IDs, required
#'   with \code{distmethod = "crossvalidated_euclidean"}. Repeated observations
#'   of a condition are averaged within each partition. Its unique values must
#'   equal \code{design$condition_ids}; the RDM order comes from the design.
#' @param crossval Independent-partition specification, for example
#'   \code{blocked_cross_validation(run_ids)}. Required only for crossvalidated
#'   Euclidean RSA and stored as \code{model$crossval}. Partitions must be disjoint,
#'   nonempty, exhaustive and at least two in number. Every condition must be
#'   observed in every partition. Missing cells are rejected at construction;
#'   nonfinite neural values fail the affected ROI rather than becoming zeros.
#'
#' @section Crossvalidated Euclidean distances:
#' For each distinct condition pair, average the inner products of its difference
#' patterns over all ordered pairs of independent partitions, then divide by the
#' number of features. This estimates a squared Euclidean distance per feature,
#'   in squared input units, and retains negative estimates. No whitening is
#' performed: this is not a Mahalanobis distance. All declared ROI features,
#' including constant columns, are retained in the normalization; nonfinite
#' columns fail the ROI instead of being removed by the shared ROI filter. Independent run IDs must be
#' supplied separately from the unique condition IDs used by the feature RDMs.
#' The caller is responsible for physical independence of partitions.
#'
#' This mode supports ordinary \code{rsa_design}, \code{measure = "distance"},
#' and the general searchlight dispatcher (\code{engine = "auto"} or
#' \code{"legacy"}). Optimized engines, including \code{"rsa_fast"}, are
#' explicitly rejected. Correlation fits use \code{regtype} to select Pearson
#' or Spearman association; historical correlation-distance behavior is unchanged.
#' It does not change \code{contrast_rsa_model}'s second-moment estimand.
#' Item permutations relabel conditions jointly across all partitions and must
#' preserve an explicit pair mask; specify suitable exchangeability blocks using
#' \code{block_var} and \code{keep_intra_run = TRUE} when retaining within-block
#' pairs. Pair masks alone do not establish exchangeability.
#'
#' @section Relational coefficients:
#' Combine \code{pair_rsa_design(..., modulation = ...)} with
#' \code{measure = "similarity", regtype = "lm", statistic = "beta"} to
#' estimate modulated relationships. For balanced one-to-one correspondence
#' and retrieval-observation intercepts, these coefficients equal regression
#' on matching-minus-nonmatching ERA scores. Unequal eligible candidate counts
#' generally imply a weighted reduction. Coefficient queries are conditional
#' on the specified measurement and fixed templates; they do not correct
#' first-level measurement bias or error in estimated neural predictors.
#' Pair cells are dependent. These outputs provide participant-level effects,
#' not calibrated standard errors or population inference. Existing label
#' permutations retain their joint-null restriction for multiple predictors;
#' they do not test a modulation coefficient conditional on other terms.
#'
#' @section Effective support of the design:
#' RDM entries are not independent observations. Every item enters
#' \code{n_items - 1} pairs, so the \code{n_pairs} entries of a vectorised RDM
#' carry on the order of \code{n_items} independent pieces of information, and
#' a regression coefficient's variance is inflated further by the predictor's
#' collinearity with the others (its VIF). The constructor computes
#' \code{n_items / VIF} for every predictor and stores the result as
#' \code{design_diagnostics} (see \code{\link{rsa_design_diagnostics}}). When
#' \code{regtype} is \code{"lm"} or \code{"rfit"} and a model predictor falls
#' below 10 effective items, it warns: that coefficient will vary across ROIs
#' largely through noise. This is a heuristic screen, not a test.
#'
#' For inference on RSA maps use \code{\link{run_permutation_searchlight}},
#' which permutes item labels and so carries the same dependence into the
#' null. For regression with multiple design predictors (including nuisance
#' predictors), this supports only an explicit joint no-association null via
#' \code{permutation_control(rsa_null = "joint")}; it does not provide
#' conditional inference on individual coefficients. The per-ROI t-values
#' returned by \code{regtype = "lm"} use pair-based degrees of freedom and
#' are anti-conservative.
#'
#' @return An object of class \code{"rsa_model"} (and \code{"list"}), containing:
#' \itemize{
#'   \item \code{dataset}    : the input dataset
#'   \item \code{design}     : the RSA design
#'   \item \code{distmethod} : the distance method used
#'   \item \code{regtype}    : the regression type
#'   \item \code{nneg}       : a named list of constrained variables, if any
#'   \item \code{semipartial}: whether to compute semi-partial correlations
#'   \item \code{design_diagnostics}: an \code{rsa_design_diagnostics} object
#'         (see \code{\link{rsa_design_diagnostics}})
#' }
#' @examples
#' # Create a random MVPA dataset (image data)
#' arr  <- array(rnorm(100 * 5), c(5, 5, 4, 5))   # 5 voxels x 5 voxels x 4 slices x 5 observations
#' sp   <- neuroim2::NeuroSpace(c(5, 5, 4, 5))
#' vec  <- neuroim2::NeuroVec(arr, sp)
#' mask <- neuroim2::LogicalNeuroVol(array(1, c(5, 5, 4)), neuroim2::NeuroSpace(c(5, 5, 4)))
#' mvpa_data <- mvpa_dataset(train_data = vec, mask = mask)
#'
#' # Create two random RDMs (distance matrices) over the 5 observations
#' data_mat  <- matrix(rnorm(5 * 10), 5, 10)
#' dismat1   <- dist(data_mat)
#' dismat2   <- dist(matrix(rnorm(5 * 10), 5, 10))
#' rdes <- rsa_design(~ dismat1 + dismat2,
#'                    list(dismat1 = dismat1, dismat2 = dismat2))
#'
#' # Create an RSA model with standard 'lm' (returns t-values):
#' rsa_mod <- rsa_model(mvpa_data, rdes, regtype = "lm")
#'
#' # Create an RSA model enforcing non-negativity for dismat2 only:
#' # Requires the 'glmnet' package to be installed
#' # rsa_mod_nneg <- rsa_model(mvpa_data, rdes, regtype="lm",
#' #                          nneg = list(dismat2 = TRUE))
#'
#' # Create an RSA model using 'lm' but returning semi-partial correlations:
#' rsa_mod_sp <- rsa_model(mvpa_data, rdes, regtype = "lm",
#'                         semipartial = TRUE)
#'
#' # Train the model using a trial-by-feature matrix
#' fit_params <- train_model(rsa_mod_sp, data_mat, y = NULL, indices = NULL)
#' # 'fit_params' = named vector of semi-partial correlations for each predictor
#'
#' # Condition-level feature RSA across three independent runs:
#' ids <- paste0("item", 1:6)
#' recording <- rep(1:2, each = 3)
#' pairs <- outer(recording, recording, `==`)
#' diag(pairs) <- FALSE
#' cv_design <- rsa_design(~ feature, list(feature = dist(1:6)),
#'                         condition_ids = ids, pair_mask = pairs)
#' cv_data <- gen_sample_dataset(c(2, 2, 2), 18, blocks = 3)$dataset
#' cv_model <- rsa_model(cv_data, cv_design,
#'   distmethod = "crossvalidated_euclidean",
#'   condition_labels = rep(ids, 3),
#'   crossval = blocked_cross_validation(rep(1:3, each = 6)))
#' # run_searchlight(cv_model, radius = 4, engine = "legacy")
#' # Six recordings with ten unique conditions each would retain 270 pairs.
#'
#' @export
rsa_model <- function(dataset,
                      design,
                      distmethod = "spearman",
                      regtype = "pearson",
                      check_collinearity = TRUE,
                      nneg = NULL,
                      semipartial = FALSE,
                      pattern_center = c("none", "stimulus_mean"),
                      return_fingerprint = FALSE,
                      fingerprint_method = c("pearson", "spearman"),
                      fingerprint_basis = c("pca", "qr"),
                      measure = c("distance", "similarity"),
                      statistic = NULL,
                      contrasts = NULL,
                      condition_labels = NULL,
                      crossval = NULL) {

  assert_that(inherits(dataset, "mvpa_dataset"))
  assert_that(inherits(design, "rsa_design"))

  distmethod <- match.arg(distmethod, c("pearson", "spearman", "crossvalidated_euclidean"))
  regtype    <- match.arg(regtype, c("pearson", "spearman", "lm", "rfit"))
  pattern_center <- match.arg(pattern_center)
  fingerprint_method <- match.arg(fingerprint_method)
  fingerprint_basis  <- match.arg(fingerprint_basis)
  measure <- match.arg(measure)
  if (!is.null(statistic)) statistic <- match.arg(statistic, "beta")
  if (!is.null(statistic) &&
      (!identical(regtype, "lm") || isTRUE(semipartial) || length(nneg))) {
    stop("`statistic = 'beta'` requires unconstrained regtype = 'lm' and semipartial = FALSE.",
         call. = FALSE)
  }
  if (!is.null(contrasts) && !identical(statistic, "beta")) {
    stop("`contrasts` requires statistic = 'beta'.", call. = FALSE)
  }
  
  # Check for glmnet if nneg constraints are provided
  if (!is.null(nneg) && length(nneg) > 0 && regtype == "lm") {
    if (!requireNamespace("glmnet", quietly = TRUE)) {
      stop("Package 'glmnet' is required for non-negative constraints. Please install it with: install.packages('glmnet')")
    }
  }
  
  # If using LM, optionally check for collinearity
  if (regtype == "lm" && check_collinearity && is.null(statistic)) {
    message("Checking design matrix for collinearity...")
    check_collinearity(design$model_mat)
    message("Collinearity check passed.")
  }

  # Verify that the number of observations in the dataset matches
  # the size expected by the RSA design. This prevents obscure
  # dimension errors later during model fitting.
  nobs_dataset <- {
    dims <- dim(dataset$train_data)
    if (is.null(dims)) length(dataset$train_data) else dims[length(dims)]
  }

  condition_design <- NULL
  if (identical(distmethod, "crossvalidated_euclidean")) {
    if (inherits(design, "pair_rsa_design") || !identical(measure, "distance")) {
      stop("Crossvalidated Euclidean RSA requires ordinary `rsa_design` and measure = 'distance'.", call. = FALSE)
    }
    condition_design <- .rsa_validate_partitions(design, condition_labels, crossval, nobs_dataset)
    if (any(!is.finite(unlist(design$model_mat)))) {
      stop("Crossvalidated RSA requires finite included predictor/nuisance pairs; supply an explicit `pair_mask`.", call. = FALSE)
    }
  } else if (!is.null(condition_labels) || !is.null(crossval)) {
    stop("`condition_labels` and `crossval` require distmethod = 'crossvalidated_euclidean'.", call. = FALSE)
  }

  if (inherits(design, "pair_rsa_design")) {
    pair_kind_chk <- design$pair_kind %||% "within"
    raw_len <- if (identical(pair_kind_chk, "between")) {
      design$n_a * design$n_b
    } else {
      choose(design$n_a, 2)
    }
    if (identical(pair_kind_chk, "between")) {
      max_row <- max(c(design$row_idx_a, design$row_idx_b))
      if (max_row > nobs_dataset) {
        stop(sprintf(
          "row_idx_a/row_idx_b reference row %d but dataset has %d observations.",
          max_row, nobs_dataset
        ), call. = FALSE)
      }
    } else if (!is.null(design$row_idx_a)) {
      max_row <- max(design$row_idx_a)
      min_row <- min(design$row_idx_a)
      if (max_row > nobs_dataset || min_row < 1L) {
        stop(sprintf(
          "row_idx_a references rows outside the dataset observations [1, %d].",
          nobs_dataset
        ), call. = FALSE)
      }
    } else if (design$n_a != nobs_dataset) {
      stop(sprintf(
        "Mismatch between dataset observations (%d) and pair_rsa_design n_a (%d). Use `row_idx_a` for within-mode subset/reordered designs.",
        nobs_dataset, design$n_a
      ), call. = FALSE)
    }
    expected_len <- if (!is.null(design$include)) sum(design$include) else raw_len
  } else {
    n_design_items <- .rsa_design_entry_size(design$data[[1L]])
    expected_items <- if (is.null(condition_design)) nobs_dataset else length(design$condition_ids)
    if (n_design_items != expected_items) {
      stop("Mismatch between dataset observations/conditions and RSA design items.", call. = FALSE)
    }
    expected_len <- choose(expected_items, 2)
    if (!is.null(design$include)) {
      expected_len <- sum(design$include)
    }
  }

  model_vec_len <- length(design$model_mat[[1]])
  if (model_vec_len != expected_len) {
    stop(sprintf(
      "Mismatch between dataset observations (%s) and RSA design length (%s).",
      nobs_dataset, model_vec_len
    ))
  }

  design_diagnostics <- rsa_design_diagnostics(design)
  if (regtype %in% c("lm", "rfit") && isTRUE(check_collinearity)) {
    .rsa_warn_effective_support(design_diagnostics, design)
  }

  fast_kernel <- NULL
  coefficient_query <- if (identical(statistic, "beta")) {
    .rsa_coefficient_query(design$model_mat, design$model_predictors, contrasts)
  } else NULL
  if (.rsa_fast_kernel_enabled() && is.null(statistic)) {
    fast_kernel <- .rsa_prepare_fast_kernel(
      design = design,
      regtype = regtype,
      distmethod = if (identical(distmethod, "crossvalidated_euclidean")) regtype else distmethod,
      semipartial = semipartial,
      nneg = nneg
    )
  }

  fingerprint_basis_obj <- NULL
  if (isTRUE(return_fingerprint)) {
    fingerprint_basis_obj <- .rsa_build_fingerprint_basis(
      design = design,
      method = fingerprint_method,
      basis  = fingerprint_basis
    )
  }

  # Create the RSA model object
  obj <- create_model_spec(
    "rsa_model",
    dataset,
    design,
    distmethod = distmethod,
    crossval = crossval,
    condition_labels = condition_labels,
    .condition_design = condition_design,
    .preserve_roi_features = identical(distmethod, "crossvalidated_euclidean"),
    regtype    = regtype,
    measure    = measure,
    statistic  = statistic,
    contrasts  = contrasts,
    nneg       = nneg,
    semipartial = semipartial,
    pattern_center = pattern_center,
    return_fingerprint = isTRUE(return_fingerprint),
    fingerprint_method = fingerprint_method,
    fingerprint_basis  = fingerprint_basis,
    design_diagnostics = design_diagnostics,
    .fast_kernel = fast_kernel,
    .coefficient_query = coefficient_query,
    .fingerprint_basis = fingerprint_basis_obj
  )
  obj
}


#' @noRd
.rsa_validate_partitions <- function(design, condition_labels, crossval, nobs) {
  ids <- design$condition_ids
  if (is.null(ids) || length(ids) < 2L) {
    stop("Crossvalidated RSA requires explicit `condition_ids` in RDM order in rsa_design().", call. = FALSE)
  }
  if (!is.atomic(condition_labels) || !is.null(dim(condition_labels)) ||
      length(condition_labels) != nobs || anyNA(condition_labels) ||
      !setequal(as.character(condition_labels), ids)) {
    stop("`condition_labels` must align with dataset rows and contain exactly the design's condition IDs.", call. = FALSE)
  }
  if (!inherits(crossval, "cross_validation")) {
    stop("Crossvalidated RSA requires an independent-partition `crossval` specification.", call. = FALSE)
  }
  nf <- get_nfolds(crossval)
  if (length(nf) != 1L || !is.finite(nf) || nf < 2L || nf != as.integer(nf)) {
    stop("Crossvalidated RSA requires at least two independent partitions.", call. = FALSE)
  }
  partitions <- lapply(seq_len(nf), function(i) partition_indices(crossval, i, n_samples = nobs))
  valid <- vapply(partitions, function(i) is.numeric(i) && length(i) > 0L &&
    all(is.finite(i)) && all(i == as.integer(i)) && all(i >= 1L & i <= nobs), logical(1))
  all_rows <- unlist(partitions, use.names = FALSE)
  if (!all(valid) || anyDuplicated(all_rows) || !setequal(all_rows, seq_len(nobs))) {
    stop("Crossvalidated RSA partitions must be nonempty, disjoint and cover every observation exactly once.", call. = FALSE)
  }
  complete <- vapply(partitions, function(i) all(ids %in% as.character(condition_labels[i])), logical(1))
  if (!all(complete)) {
    stop("Missing condition/partition observations: every condition must occur in every partition; no zero imputation or pairwise deletion is performed.", call. = FALSE)
  }
  mvpa_design(data.frame(condition = factor(condition_labels, levels = ids)),
              y_train = ~ condition,
              block_var = if (inherits(crossval, "blocked_cross_validation")) crossval$block_var else NULL)
}

#' @noRd
.rsa_crossvalidated_response <- function(obj, train_dat) {
  if (!is.matrix(train_dat) || !is.numeric(train_dat) || ncol(train_dat) < 1L ||
      nrow(train_dat) != length(obj$condition_labels) || any(!is.finite(train_dat))) {
    stop("Crossvalidated RSA requires finite observation-by-feature data with all declared rows; missing values are not imputed.", call. = FALSE)
  }
  folds <- compute_crossvalidated_means_sl(
    train_dat, obj$.condition_design, obj$crossval,
    estimation_method = "crossnobis", return_folds = TRUE
  )$fold_estimates
  if (!is.null(obj$design$item_perm)) {
    rows <- .rsa_apply_item_perm(seq_len(dim(folds)[1L]), obj$design$item_perm)
    folds <- folds[rows, , , drop = FALSE]
  }
  compute_crossnobis_distances_sl(folds)
}

#' @keywords internal
#' @noRd
.rsa_build_fingerprint_basis <- function(design, method, basis, tol = 1e-8) {
  predictor_names <- names(design$model_mat)
  model_predictors <- design$model_predictors
  if (is.null(model_predictors)) {
    model_predictors <- predictor_names
  }
  model_predictors <- intersect(model_predictors, predictor_names)
  if (length(model_predictors) == 0L) {
    stop("`return_fingerprint = TRUE` requires at least one signal model predictor; nuisance-only designs do not define a model-space fingerprint.",
         call. = FALSE)
  }
  mat <- do.call(cbind, design$model_mat[model_predictors])
  if (!is.matrix(mat) || ncol(mat) == 0L || nrow(mat) < 2L) {
    return(NULL)
  }
  storage.mode(mat) <- "double"
  X <- .rdm_model_space_standardize_matrix(mat, method = method, tol = tol,
                                           label = "model_mat")
  bf <- .rdm_model_space_basis(X, basis = basis, tol = tol)
  list(
    Q          = bf$Q,
    axis_names = bf$axis_names,
    method     = method,
    basis      = basis,
    p          = nrow(X),
    tol        = tol
  )
}


#' @keywords internal
#' @noRd
.rsa_project_fingerprint <- function(dvec, fp) {
  if (is.null(fp) || is.null(fp$Q)) return(NULL)
  if (length(dvec) != fp$p) return(NULL)

  v <- as.numeric(dvec)
  if (identical(fp$method, "spearman")) {
    v <- rank(v, ties.method = "average")
  }
  v <- v - mean(v)
  s <- stats::sd(v)
  if (!is.finite(s) || s <= fp$tol) {
    out <- rep(NA_real_, ncol(fp$Q))
    names(out) <- fp$axis_names
    return(out)
  }
  v <- v / s
  scores <- drop(crossprod(fp$Q, v)) / sqrt(fp$p - 1L)
  names(scores) <- fp$axis_names
  scores
}


#' @keywords internal
#' @noRd
.rsa_attach_fingerprint <- function(out, dvec, fp) {
  scores <- .rsa_project_fingerprint(dvec, fp)
  if (is.null(scores)) return(out)
  attr(out, "fingerprint") <- scores
  out
}

#' @rdname output_schema
#' @method output_schema rsa_model
#' @export
output_schema.rsa_model <- function(model) {
  predictor_names <- if (identical(model$statistic, "beta")) {
    rownames(model$.coefficient_query$query)
  } else names(model$design$model_mat)
  schema <- as.list(rep("scalar", length(predictor_names)))
  names(schema) <- predictor_names
  schema
}
